# Generated by Django 4.2.24 on 2025-09-13 22:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_options_rename_owner_note_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='kind',
            field=models.CharField(choices=[('shopping', 'Shopping'), ('ideas', 'Ideas'), ('goals', 'Goals'), ('routine', 'Routine')], max_length=16),
        ),
        migrations.AlterField(
            model_name='note',
            name='labels',
            field=models.ManyToManyField(blank=True, to='notes.label'),
        ),
        migrations.RemoveField(
            model_name='label',
            name='user',
        ),
    ]
